name: Java CI with Maven

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      env:
        google-client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
        google-client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        cloudinary-name: ${{ secrets.CLOUDINARY_NAME }}
        cloudinary-api-secret: ${{ secrets.CLOUDINARY_API_SECRET }}
        cloudinary-api-key: ${{ secrets.CLOUDINARY_API_KEY }}
      run: mvn -B package --file pom.xml
